-- Instance seed: marketplace branding (AhadaBuldum deployment)

INSERT INTO public.marketplace_settings (
  marketplace_name,
  short_name,
  logo_url,
  logo_dark_url,
  favicon_url,
  primary_color,
  secondary_color,
  accent_color,
  support_email,
  support_phone,
  company_name,
  default_currency,
  default_country,
  default_locale,
  seo_title,
  seo_description,
  tagline,
  social_links
) VALUES (
  'AhadaBuldum',
  'AhadaBuldum',
  NULL,
  NULL,
  NULL,
  '#0A4D8C',
  '#1A6B9A',
  '#FF6B1A',
  'destek@ahadabuldum.com',
  NULL,
  'AhadaBuldum',
  'TRY',
  'TR',
  'tr',
  'AhadaBuldum — Türkiye''nin Teknik Ürünler Pazaryeri',
  'Boru, hırdavat, vana ve altyapı malzemeleri — güvenilir satıcılardan tek platformda',
  'Teknik ürünleri güvenle, hızla, doğru yerden bul.',
  '{}'::JSONB
)
ON CONFLICT ((true)) DO UPDATE SET
  marketplace_name = EXCLUDED.marketplace_name,
  short_name = EXCLUDED.short_name,
  logo_url = EXCLUDED.logo_url,
  logo_dark_url = EXCLUDED.logo_dark_url,
  favicon_url = EXCLUDED.favicon_url,
  primary_color = EXCLUDED.primary_color,
  secondary_color = EXCLUDED.secondary_color,
  accent_color = EXCLUDED.accent_color,
  support_email = EXCLUDED.support_email,
  support_phone = EXCLUDED.support_phone,
  company_name = EXCLUDED.company_name,
  default_currency = EXCLUDED.default_currency,
  default_country = EXCLUDED.default_country,
  default_locale = EXCLUDED.default_locale,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  tagline = EXCLUDED.tagline,
  social_links = EXCLUDED.social_links,
  updated_at = now();
